export const resData =[
  {
    Id: 1027,
    PrevVendorId: 1027,
    Name: "4 Corners - Detroit Style Pizza",
    VendorType: "REGULAR",
    VendorShortCut: "4 Corners - Detroit Style Pizza",
    BannerImageOne: null,
    BannerImageTwo: null,
    ShortName: "4 Corners - Detroit Style Pizza",
    PhoneNumber1: "",
    PhoneNumber2: "",
    ContactPerson1: "",
    ContactPerson2: "",
    Address1: "Sanepa",
    Address2: "Sanepa",
    Distance: 2.8,
    DeliveryDistanceStr: "Approx 2.8 km",
    IsFavouriteVendor: 0,
    IsFavorite: 0,
    IsVATApplicable: 0,
    VAT: 0,
    ServiceCharge: 0,
    Speciality:
      "Double Pepperoni Pizza | BBQ Chicken Pizza | Honey Spinach Bianca Pizza | Meat Lover Pizza | Margherita Pizza",
    Description:
      "Detroit-style Pizza!!! Might look small but these deep-dish pizzas are for sharing! 1/2kg pizza’s, Pepperoni, homemade Sausage, Ricotta and more.",
    Cuisine: "Italian",
    MinimumOrderAmount: 0,
    LocationLat: 27.687932,
    LocationLng: 85.308291,
    IsVendorClosed: false,
    CloseNotice: "",
    GridViewAvailable: false,
    SubMenuVisibility: false,
    DefaultView: "LIST",
    RecurringOrderAvailable: true,
    RecurringOrderAvailableDays: "",
    MaxRecurringOrderDate: "1900-01-01T00:00:00",
    HasDeal: false,
    DealDescription: "",
    AcceptsTakeoutOrder: false,
    AcceptsDeliveryOrder: true,
    OpeningTime: "12:30 PM",
    ClosingTime: "8:45 PM",
    ImageName: "6_151222081324._4-cornors-web.listing.jpg",
    ImagePath: "https://images.foodmandu.com//Images/Vendor/1027/OriginalSize/",
    LogoName: "AppWeb_copy_4_090824061522.png",
    ShoppingCartId: 0,
    VendorListingWebImageName:
      "https://images.foodmandu.com//Images/Vendor/1027/OriginalSize/Untitled_design_-_2024-06-10T160909_100624102433.920.png",
    VendorCoverImageName:
      "https://images.foodmandu.com//Images/Vendor/1027/OriginalSize/4_corner_050624071057.png",
    VendorLogoImageName:
      "https://images.foodmandu.com//Images/Vendor/1027/OriginalSize/AppWeb_copy_4_090824061522.png",
    allowAR: false,
    radiusAR: 4,
    multivendor: false,
    VendorWebSite: "https://foodmandu.com/Restaurant/Details/1027",
    VendorShareLink: "https://foodmandu.com/Restaurant/Details/1027",
    PromoTitle: "",
    PromoText: "",
    VendorNotice: "",
    ItemAddWarning:
      "This restaurant/store is closed for delivery at the moment. However, you can pre-order for later.",
    Delivering: true,
    NotDeliveryMessage: "",
    NotDeliveryMessageColor: "#9D0A0E",
    DeliveryDuration: "",
    DeliveryChargeStr: "",
    DeliveryCharge: {
      color: "#0c0d0c",
      font_size: 12,
      charge: "Rs. 20/KM",
    },
    AllowSortByCategory: false,
    BeyoundHoursWarning: "CLOSE NOW",
    VendorRating: "4.34",
    TotalReview: "275",
    HasRating: true,
    NoReviewMessage: "",
    deliveryTimeInfo: "",
  },
  {
    Id: 269,
    PrevVendorId: 0,
    Name: "Fire And Ice Pizzeria - Thamel",
    VendorType: "REGULAR",
    VendorShortCut: "fireNice",
    BannerImageOne: null,
    BannerImageTwo: null,
    ShortName: "Fire And Ice Pizzeria - Thamel",
    PhoneNumber1: "",
    PhoneNumber2: "",
    ContactPerson1: "",
    ContactPerson2: "",
    Address1: "Thamel",
    Address2: "Thamel",
    Distance: 1.9,
    DeliveryDistanceStr: "Approx 1.9 km",
    IsFavouriteVendor: 0,
    IsFavorite: 0,
    IsVATApplicable: 0,
    VAT: 0,
    ServiceCharge: 0,
    Speciality: "Margherita Pizza | L'Americana Pizza | Funghi Pizza",
    Description:
      '<p align="Justify"><b>Fire and Ice</b><br/>\nThis is  firstly opened its doors in January 1995. It immediately became a very popular restaurant among travelers, climbers and local residents as the place to meet for a morning cup of Italian espresso, or later on in the day to share stories and travel tales with friends whilst savoring delicious Pizza, Pastas, Organic Salads, Deserts and even a Grappa after Dinner.</p> ',
    Cuisine: "Italian",
    MinimumOrderAmount: 0,
    LocationLat: 27.713579,
    LocationLng: 85.313516,
    IsVendorClosed: false,
    CloseNotice: "",
    GridViewAvailable: false,
    SubMenuVisibility: false,
    DefaultView: "LIST",
    RecurringOrderAvailable: true,
    RecurringOrderAvailableDays: "",
    MaxRecurringOrderDate: "1900-01-01T00:00:00",
    HasDeal: false,
    DealDescription: "",
    AcceptsTakeoutOrder: false,
    AcceptsDeliveryOrder: true,
    OpeningTime: "11:00 AM",
    ClosingTime: "10:00 PM",
    ImageName: "2_151222080951._fire-and-ice-web.listing.jpg",
    ImagePath: "https://images.foodmandu.com//Images/Vendor/269/OriginalSize/",
    LogoName: "fireandice-web-logo_071117110319.jpg",
    ShoppingCartId: 0,
    VendorListingWebImageName:
      "https://images.foodmandu.com//Images/Vendor/269/OriginalSize/web_240423103631_200624060757.listing-fire-and-ice.png",
    VendorCoverImageName:
      "https://images.foodmandu.com//Images/Vendor/269/OriginalSize/WhatsApp_Image_2024-06-20_at_11_200624061441.59.16_AM.jpeg",
    VendorLogoImageName:
      "https://foodmandu.com//Images/Vendor/269/OriginalSize/fireandice-web-logo_071117110319.jpg",
    allowAR: false,
    radiusAR: 4,
    multivendor: false,
    VendorWebSite: "www.fireandicepizzeria.com",
    VendorShareLink: "https://foodmandu.com/Restaurant/Details/269",
    PromoTitle: "",
    PromoText: "",
    VendorNotice: "",
    ItemAddWarning: "",
    Delivering: true,
    NotDeliveryMessage: "",
    NotDeliveryMessageColor: "#9D0A0E",
    DeliveryDuration: "",
    DeliveryChargeStr: "",
    DeliveryCharge: {
      color: "#0c0d0c",
      font_size: 12,
      charge: "Rs. 20/KM",
    },
    AllowSortByCategory: false,
    BeyoundHoursWarning: "CLOSE NOW",
    VendorRating: "4.16",
    TotalReview: "313",
    HasRating: true,
    NoReviewMessage: "",
    deliveryTimeInfo: "",
  },
  {
    Id: 326,
    PrevVendorId: 0,
    Name: "The Workshop Eatery - Bakhundole",
    VendorType: "REGULAR",
    VendorShortCut: "theworkshop",
    BannerImageOne: null,
    BannerImageTwo: null,
    ShortName: "The Workshop Eatery - Bakhundole",
    PhoneNumber1: "",
    PhoneNumber2: "",
    ContactPerson1: "",
    ContactPerson2: "",
    Address1: "Bakhundole",
    Address2: "Bakhundole",
    Distance: 3.2,
    DeliveryDistanceStr: "Approx 3.2 km",
    IsFavouriteVendor: 0,
    IsFavorite: 0,
    IsVATApplicable: 0,
    VAT: 0,
    ServiceCharge: 0,
    Speciality:
      "Nashville Style Chicken Burger | Spicy Chicken Sandwich | Classic Glazed Doughnut | Fries",
    Description:
      '"Burger. Fries. Wraps. Doughnuts"\n#Vegetarian Friendly (includes eggs)\n#Halal Friendly (only chicken)\n#Not Vegan Friendly',
    Cuisine: "American",
    MinimumOrderAmount: 0,
    LocationLat: 27.683185,
    LocationLng: 85.311424,
    IsVendorClosed: false,
    CloseNotice: "",
    GridViewAvailable: false,
    SubMenuVisibility: false,
    DefaultView: "LIST",
    RecurringOrderAvailable: true,
    RecurringOrderAvailableDays: "",
    MaxRecurringOrderDate: "1900-01-01T00:00:00",
    HasDeal: false,
    DealDescription: "",
    AcceptsTakeoutOrder: false,
    AcceptsDeliveryOrder: true,
    OpeningTime: "8:00 AM",
    ClosingTime: "8:30 PM",
    ImageName: "1_151222080829._workshop-eatery-web.listing.jpg",
    ImagePath: "https://images.foodmandu.com//Images/Vendor/326/OriginalSize/",
    LogoName: "untitled_design_-_2024-11-12t161845_121124103426.926_480.png",
    ShoppingCartId: 0,
    VendorListingWebImageName:
      "https://images.foodmandu.com//Images/Vendor/326/OriginalSize/Untitled_design_-_2024-06-11T112136_110624053658.455.png",
    VendorCoverImageName:
      "https://images.foodmandu.com//Images/Vendor/326/OriginalSize/Untitled_design_-_2024-09-05T165604_050924111110.600.png",
    VendorLogoImageName:
      "https://images.foodmandu.com//Images/Vendor/326/OriginalSize/untitled_design_-_2024-11-12t161845_121124103426.926_480.png",
    allowAR: false,
    radiusAR: 4,
    multivendor: false,
    VendorWebSite: "https://foodmandu.com/Restaurant/Details/326",
    VendorShareLink: "https://foodmandu.com/Restaurant/Details/326",
    PromoTitle: "",
    PromoText: "",
    VendorNotice: "",
    ItemAddWarning:
      "This restaurant/store is closed for delivery at the moment. However, you can pre-order for later.",
    Delivering: true,
    NotDeliveryMessage: "",
    NotDeliveryMessageColor: "#9D0A0E",
    DeliveryDuration: "",
    DeliveryChargeStr: "",
    DeliveryCharge: {
      color: "#0c0d0c",
      font_size: 12,
      charge: "Rs. 20/KM",
    },
    AllowSortByCategory: false,
    BeyoundHoursWarning: "CLOSE NOW",
    VendorRating: "4.30",
    TotalReview: "704",
    HasRating: true,
    NoReviewMessage: "",
    deliveryTimeInfo: "",
  },
  {
    Id: 232,
    PrevVendorId: 0,
    Name: "Le Trio - Jhamsikhel",
    VendorType: "REGULAR",
    VendorShortCut: "Le Trio - Jhamsikhel",
    BannerImageOne: null,
    BannerImageTwo: null,
    ShortName: "Le Trio - Jhamsikhel",
    PhoneNumber1: "",
    PhoneNumber2: "",
    ContactPerson1: "",
    ContactPerson2: "",
    Address1: "Jhamsikhel",
    Address2: "Jhamsikhel",
    Distance: 4,
    DeliveryDistanceStr: "Approx 4.0 km",
    IsFavouriteVendor: 0,
    IsFavorite: 0,
    IsVATApplicable: 0,
    VAT: 0,
    ServiceCharge: 0,
    Speciality: "Jhol Mo:Mo | Spaghetti | Buffalo Wings",
    Description:
      '<p align="Justify"><Le Trio</b><br/>\nAs the name suggests, Le Trio has three owners. Their passion for good hygienic food inspired them establish this restaurant in Jhamsikhel, Pulchwok. Le Trio is best known for its <strong> Mo:Mo Cha with Jhol Achar</strong>. Trio Momo Cha are freshly made only on demand. This multi cuisine restaurant has a cozy indoor seating area with a separate space for smokers and non-smokers. Other menu highlights are Crispy Potatoes, Buffalo Wings, and the scrumptious desserts.<br/>\n <br/>\nTrio may seem small for a proper restaurant, but the food and the hospitality will not leave you disappointed. There is something special about this restaurant that will have you going back again and again.</p> <br/>\n',
    Cuisine: "Nepali | Continental",
    MinimumOrderAmount: 0,
    LocationLat: 27.675797,
    LocationLng: 85.314108,
    IsVendorClosed: false,
    CloseNotice: "",
    GridViewAvailable: false,
    SubMenuVisibility: false,
    DefaultView: "LIST",
    RecurringOrderAvailable: true,
    RecurringOrderAvailableDays: "",
    MaxRecurringOrderDate: "1900-01-01T00:00:00",
    HasDeal: false,
    DealDescription: "",
    AcceptsTakeoutOrder: false,
    AcceptsDeliveryOrder: true,
    OpeningTime: "11:00 AM",
    ClosingTime: "9:00 PM",
    ImageName: "7_151222081350._le-trio-web.listing.jpg",
    ImagePath: "https://images.foodmandu.com//Images/Vendor/232/OriginalSize/",
    LogoName: "letrio_081117061917.jpg",
    ShoppingCartId: 0,
    VendorListingWebImageName:
      "https://images.foodmandu.com//Images/Vendor/232/OriginalSize/Untitled_design_-_2024-06-10T172330_100624113837.765.png",
    VendorCoverImageName:
      "https://images.foodmandu.com//Images/Vendor/232/OriginalSize/Le_trio_050624071216.png",
    VendorLogoImageName:
      "https://foodmandu.com//Images/Vendor/232/OriginalSize/letrio_081117061917.jpg",
    allowAR: false,
    radiusAR: 4,
    multivendor: false,
    VendorWebSite: "https://foodmandu.com/Restaurant/Details/232",
    VendorShareLink: "https://foodmandu.com/Restaurant/Details/232",
    PromoTitle: "",
    PromoText: "",
    VendorNotice: "",
    ItemAddWarning:
      "This restaurant/store is closed for delivery at the moment. However, you can pre-order for later.",
    Delivering: true,
    NotDeliveryMessage: "",
    NotDeliveryMessageColor: "#9D0A0E",
    DeliveryDuration: "",
    DeliveryChargeStr: "",
    DeliveryCharge: {
      color: "#0c0d0c",
      font_size: 12,
      charge: "Rs. 20/KM",
    },
    AllowSortByCategory: false,
    BeyoundHoursWarning: "CLOSE NOW",
    VendorRating: "3.64",
    TotalReview: "70",
    HasRating: true,
    NoReviewMessage: "",
    deliveryTimeInfo: "",
  },
  {
    Id: 289,
    PrevVendorId: 0,
    Name: "Burger Shack - Jawalakhel",
    VendorType: "REGULAR",
    VendorShortCut: "Burger Shack - Jawalakhel",
    BannerImageOne: null,
    BannerImageTwo: null,
    ShortName: "Burger Shack - Jawalakhel",
    PhoneNumber1: "",
    PhoneNumber2: "",
    ContactPerson1: "",
    ContactPerson2: "",
    Address1: "Jawalakhel",
    Address2: "Jawalakhel",
    Distance: 4.5,
    DeliveryDistanceStr: "Approx 4.5 km",
    IsFavouriteVendor: 0,
    IsFavorite: 0,
    IsVATApplicable: 0,
    VAT: 0,
    ServiceCharge: 0,
    Speciality: "Baconiser | Onion Rings | Double Melt",
    Description:
      '<p align="Justify"><b>Burger Shack</b> <br/>\n<i>Thinking about best Burger in Town?!!!.Good!!</i><br/>\nBurger Shack is here to serve you with the best burger in town. Appraised with lots of positive comments and admired by tons of burger lovers, Burger Shack has become the ultimate destination in Kathmandu city among citizens of Kathmandu.Burger Shack  serves hundreds of customer in daily basis. Adequate dining space and prompt service molds it as outstanding from the rest of the burger places in Kathmandu. <br/>\n<br/>\nIn another hand, it offers you to select arrays of extra fillings and selective items that you would just love your burger to be.Burger Shack has taken Burger\'s authentic taste, quality and presentation to the next level.It has two outlets currently in Kathmandu and Lalitpur coping with the high demands of customers.Quality conscious staff and service team makes it one of the suitable place to seat, enjoy and eat.   </p>',
    Cuisine: "American",
    MinimumOrderAmount: 0,
    LocationLat: 27.672494,
    LocationLng: 85.313839,
    IsVendorClosed: false,
    CloseNotice: "",
    GridViewAvailable: false,
    SubMenuVisibility: false,
    DefaultView: "LIST",
    RecurringOrderAvailable: true,
    RecurringOrderAvailableDays: "",
    MaxRecurringOrderDate: "1900-01-01T00:00:00",
    HasDeal: false,
    DealDescription: "",
    AcceptsTakeoutOrder: false,
    AcceptsDeliveryOrder: true,
    OpeningTime: "12:00 PM",
    ClosingTime: "8:00 PM",
    ImageName: "4_151222081103._burger-shack-web-listing.jpg",
    ImagePath: "https://images.foodmandu.com//Images/Vendor/289/OriginalSize/",
    LogoName: "Burger_shack_logo_(1)_090824061102.png",
    ShoppingCartId: 0,
    VendorListingWebImageName:
      "https://images.foodmandu.com//Images/Vendor/289/OriginalSize/4_151222081130_150424053129._burger-shack-web-listing.jpg",
    VendorCoverImageName:
      "https://images.foodmandu.com//Images/Vendor/289/OriginalSize/Burger_Shack_-_Kamaladi_070425052021.png",
    VendorLogoImageName:
      "https://images.foodmandu.com//Images/Vendor/289/OriginalSize/Burger_shack_logo_(1)_090824061102.png",
    allowAR: false,
    radiusAR: 4,
    multivendor: false,
    VendorWebSite: "https://foodmandu.com/Restaurant/Details/289",
    VendorShareLink: "https://foodmandu.com/Restaurant/Details/289",
    PromoTitle: "",
    PromoText: "",
    VendorNotice: "",
    ItemAddWarning:
      "This restaurant/store is closed for delivery at the moment. However, you can pre-order for later.",
    Delivering: true,
    NotDeliveryMessage: "",
    NotDeliveryMessageColor: "#9D0A0E",
    DeliveryDuration: "",
    DeliveryChargeStr: "",
    DeliveryCharge: {
      color: "#0c0d0c",
      font_size: 12,
      charge: "Rs. 20/KM",
    },
    AllowSortByCategory: false,
    BeyoundHoursWarning: "CLOSE NOW",
    VendorRating: "4.22",
    TotalReview: "244",
    HasRating: true,
    NoReviewMessage: "",
    deliveryTimeInfo: "",
  },
  {
    Id: 978,
    PrevVendorId: 978,
    Name: "Koto Restaurant - Durbarmarg",
    VendorType: "REGULAR",
    VendorShortCut: "Koto Restaurant - Durbarmarg",
    BannerImageOne: null,
    BannerImageTwo: null,
    ShortName: "Koto Restaurant - Durbarmarg",
    PhoneNumber1: "",
    PhoneNumber2: "",
    ContactPerson1: "",
    ContactPerson2: "",
    Address1: "Durbarmarg",
    Address2: "Durbarmarg",
    Distance: 1.4,
    DeliveryDistanceStr: "Approx 1.4 km",
    IsFavouriteVendor: 0,
    IsFavorite: 0,
    IsVATApplicable: 0,
    VAT: 0,
    ServiceCharge: 0,
    Speciality:
      "Tonkatsu Bento (Chicken) | Prawn Tempura | Chicken Taki -Rouse",
    Description:
      '<p align="Justify"><b>"Koto"</b><br/>\nKoto in Japanese is a traditional Japanese instrument which is 6 feet long and contains 36 strings on it.The traditional Japanese name, reflects the authenticity of the Japanese cuisine being served at the restaurant.<br/>\n<br/>\nThe restaurant has three different outlets, one at Pulchowk and two at Durbarmarg with slight difference in the menu. You can find wide range of Japanese dishes, from cold soba noodles and mackerel dishes to sukiyaki and bento boxes, plus several set menus. All the foods are served best in terms of hygiene and presentation.  <br/>\nThe restaurant has ample parking space. However, the restaurant remains closed everyday between 3:00 PM to 5:30 PM.</p> ',
    Cuisine: "Japanese",
    MinimumOrderAmount: 0,
    LocationLat: 27.71157,
    LocationLng: 85.317375,
    IsVendorClosed: false,
    CloseNotice: "",
    GridViewAvailable: false,
    SubMenuVisibility: false,
    DefaultView: "LIST",
    RecurringOrderAvailable: true,
    RecurringOrderAvailableDays: "",
    MaxRecurringOrderDate: "1900-01-01T00:00:00",
    HasDeal: false,
    DealDescription: "",
    AcceptsTakeoutOrder: false,
    AcceptsDeliveryOrder: true,
    OpeningTime: "11:30 AM",
    ClosingTime: "9:15 PM",
    ImageName: "5_151222081218._koto-web.listing.jpg",
    ImagePath: "https://images.foodmandu.com//Images/Vendor/978/OriginalSize/",
    LogoName: "KOTO_011122101908.jpg",
    ShoppingCartId: 0,
    VendorListingWebImageName:
      "https://images.foodmandu.com//Images/Vendor/978/OriginalSize/Untitled_design_-_2024-06-10T152425_100624095135.059.png",
    VendorCoverImageName:
      "https://images.foodmandu.com//Images/Vendor/978/OriginalSize/Untitled_design_(1)_091224110447.png",
    VendorLogoImageName:
      "https://images.foodmandu.com//Images/Vendor/978/OriginalSize/KOTO_011122101908.jpg",
    allowAR: false,
    radiusAR: 4,
    multivendor: false,
    VendorWebSite: "https://foodmandu.com/Restaurant/Details/978",
    VendorShareLink: "https://foodmandu.com/Restaurant/Details/978",
    PromoTitle: "",
    PromoText: "",
    VendorNotice: "",
    ItemAddWarning:
      "This restaurant/store is closed for delivery at the moment. However, you can pre-order for later.",
    Delivering: true,
    NotDeliveryMessage: "",
    NotDeliveryMessageColor: "#9D0A0E",
    DeliveryDuration: "",
    DeliveryChargeStr: "",
    DeliveryCharge: {
      color: "#0c0d0c",
      font_size: 12,
      charge: "Rs. 20/KM",
    },
    AllowSortByCategory: false,
    BeyoundHoursWarning: "CLOSE NOW",
    VendorRating: "4.18",
    TotalReview: "51",
    HasRating: true,
    NoReviewMessage: "",
    deliveryTimeInfo: "",
  },
  {
    Id: 846,
    PrevVendorId: 846,
    Name: "Kathmandu Marriott",
    VendorType: "REGULAR",
    VendorShortCut: "Marriott",
    BannerImageOne: null,
    BannerImageTwo: null,
    ShortName: "Kathmandu Marriott",
    PhoneNumber1: "",
    PhoneNumber2: "",
    ContactPerson1: "",
    ContactPerson2: "",
    Address1: "Naxal Kathmandu",
    Address2: "Naxal Kathmandu",
    Distance: 1.4,
    DeliveryDistanceStr: "Approx 1.4 km",
    IsFavouriteVendor: 0,
    IsFavorite: 0,
    IsVATApplicable: 0,
    VAT: 0,
    ServiceCharge: 0,
    Speciality:
      "Tawa Phulka | Marriot Burger | Chara ko Masu ko Jhol | Flourless Chocolate Hazelnut | Yellow Dal Tadka | Bacocini Artigianale | Chocolate Burger | Garlic Naan",
    Description:
      "In-house patisserie serving delectable gourmet sweets, baked goodies, fresh salads and other dainties. Refreshing beverages and juices are also available for guests to enjoy onsite or for take-away.",
    Cuisine: "Indian",
    MinimumOrderAmount: 0,
    LocationLat: 27.712945,
    LocationLng: 85.324154,
    IsVendorClosed: false,
    CloseNotice: "",
    GridViewAvailable: false,
    SubMenuVisibility: false,
    DefaultView: "LIST",
    RecurringOrderAvailable: true,
    RecurringOrderAvailableDays: "",
    MaxRecurringOrderDate: "1900-01-01T00:00:00",
    HasDeal: false,
    DealDescription: "",
    AcceptsTakeoutOrder: false,
    AcceptsDeliveryOrder: true,
    OpeningTime: "11:00 AM",
    ClosingTime: "9:00 PM",
    ImageName: "8_151222081509._ktm-marritot-web.listing.jpg",
    ImagePath: "https://images.foodmandu.com//Images/Vendor/846/OriginalSize/",
    LogoName: "web_211019101447.logo.newrelease.marriott.jpg",
    ShoppingCartId: 0,
    VendorListingWebImageName:
      "https://images.foodmandu.com//Images/Vendor/846/OriginalSize/8_151222081509._ktm-marritot-web.listing.jpg",
    VendorCoverImageName:
      "https://foodmandu.com//Images/Vendor/846/OriginalSize/web_040520033827.cover.newrelease.marriott_-_Copy.jpg",
    VendorLogoImageName:
      "https://foodmandu.com//Images/Vendor/846/OriginalSize/web_211019101447.logo.newrelease.marriott.jpg",
    allowAR: false,
    radiusAR: 4,
    multivendor: false,
    VendorWebSite: "https://foodmandu.com/Restaurant/Details/846",
    VendorShareLink: "https://foodmandu.com/Restaurant/Details/846",
    PromoTitle: "",
    PromoText: "",
    VendorNotice: "",
    ItemAddWarning:
      "This restaurant/store is closed for delivery at the moment. However, you can pre-order for later.",
    Delivering: true,
    NotDeliveryMessage: "",
    NotDeliveryMessageColor: "#9D0A0E",
    DeliveryDuration: "",
    DeliveryChargeStr: "",
    DeliveryCharge: {
      color: "#0c0d0c",
      font_size: 12,
      charge: "Rs. 20/KM",
    },
    AllowSortByCategory: false,
    BeyoundHoursWarning: "CLOSE NOW",
    VendorRating: "3.83",
    TotalReview: "32",
    HasRating: true,
    NoReviewMessage: "",
    deliveryTimeInfo: "",
  },
  {
    Id: 844,
    PrevVendorId: 844,
    Name: "Burger Shack - Kamaladi",
    VendorType: "REGULAR",
    VendorShortCut: "Burger Shack - Kamaladi",
    BannerImageOne: null,
    BannerImageTwo: null,
    ShortName: "Burger Shack - Kamaladi",
    PhoneNumber1: "",
    PhoneNumber2: "",
    ContactPerson1: "",
    ContactPerson2: "",
    Address1: "Kamaladi",
    Address2: "Kamaladi",
    Distance: 1,
    DeliveryDistanceStr: "Approx 1.0 km",
    IsFavouriteVendor: 0,
    IsFavorite: 0,
    IsVATApplicable: 0,
    VAT: 0,
    ServiceCharge: 0,
    Speciality: "Baconiser | Onion Rings | Double Melt",
    Description:
      '<p align="Justify"><b>Burger Shack</b> <br/>\n<i>Thinking about best Burger in Town?!!!.Good!!</i><br/>\nBurger Shack is here to serve you with the best burger in town. Appraised with lots of positive comments and admired by tons of burger lovers, Burger Shack has become the ultimate destination in Kathmandu city among citizens of Kathmandu.Burger Shack  serves hundreds of customer in daily basis. Adequate dining space and prompt service molds it as outstanding from the rest of the burger places in Kathmandu. <br/>\n<br/>\nIn another hand, it offers you to select arrays of extra fillings and selective items that you would just love your burger to be.Burger Shack has taken Burger\'s authentic taste, quality and presentation to the next level.It has two outlets currently in Kathmandu and Lalitpur coping with the high demands of customers.Quality conscious staff and service team makes it one of the suitable place to seat, enjoy and eat.   </p>',
    Cuisine: "American",
    MinimumOrderAmount: 0,
    LocationLat: 27.710059,
    LocationLng: 85.319959,
    IsVendorClosed: false,
    CloseNotice: "",
    GridViewAvailable: false,
    SubMenuVisibility: false,
    DefaultView: "LIST",
    RecurringOrderAvailable: true,
    RecurringOrderAvailableDays: "",
    MaxRecurringOrderDate: "1900-01-01T00:00:00",
    HasDeal: false,
    DealDescription: "",
    AcceptsTakeoutOrder: false,
    AcceptsDeliveryOrder: true,
    OpeningTime: "12:00 PM",
    ClosingTime: "7:45 PM",
    ImageName: "4_151222081130._burger-shack-web-listing.jpg",
    ImagePath: "https://images.foodmandu.com//Images/Vendor/844/OriginalSize/",
    LogoName: "burger_shack_logo_290224110300.png",
    ShoppingCartId: 0,
    VendorListingWebImageName:
      "https://images.foodmandu.com//Images/Vendor/844/OriginalSize/4_151222081130_150424053157._burger-shack-web-listing.jpg",
    VendorCoverImageName:
      "https://images.foodmandu.com//Images/Vendor/844/OriginalSize/Burger_Shack_-_Kamaladi_070425052031.png",
    VendorLogoImageName:
      "https://images.foodmandu.com//Images/Vendor/844/OriginalSize/burger_shack_logo_290224110300.png",
    allowAR: false,
    radiusAR: 4,
    multivendor: false,
    VendorWebSite: "https://foodmandu.com/Restaurant/Details/844",
    VendorShareLink: "https://foodmandu.com/Restaurant/Details/844",
    PromoTitle: "",
    PromoText: "",
    VendorNotice: "",
    ItemAddWarning:
      "This restaurant/store is closed for delivery at the moment. However, you can pre-order for later.",
    Delivering: true,
    NotDeliveryMessage: "",
    NotDeliveryMessageColor: "#9D0A0E",
    DeliveryDuration: "",
    DeliveryChargeStr: "",
    DeliveryCharge: {
      color: "#0c0d0c",
      font_size: 12,
      charge: "Rs. 20",
    },
    AllowSortByCategory: false,
    BeyoundHoursWarning: "CLOSE NOW",
    VendorRating: "4.33",
    TotalReview: "243",
    HasRating: true,
    NoReviewMessage: "",
    deliveryTimeInfo: "",
  },
];
